# Generated by Django 4.1.2 on 2024-12-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata',
            name='server',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
